name: "Ukenytt"
description: "Addon som mottar ukenytt-PDF via HTTP og konverterer til Home Assistant sensorer"
version: "0.3.0"
slug: "ukenytt"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: "HTTP API for PDF-opplasting"
options:
  homeassistant_url: "http://supervisor/core"
  homeassistant_long_lived_access_token: ""
  api_key: ""
  children:
    - "frida"
schema:
  homeassistant_url: url
  homeassistant_long_lived_access_token: str
  api_key: str?
  children:
    - str
