name: "Finn no Bobil"
description: "Addon traverserer finn pÃ¥ jakt etter bobiler og lagrer historikk i database"
version: "0.2.5"
slug: "finn_no_bobil"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
options:
  databasehost: "database host"
  databaseusername: "database username"
  databasepassword: "database password"
  databasename: "database name"
  databaseport: "database port"
schema:
  databasehost: "str"
  databaseusername: "str"
  databasepassword: "str"
  databasename: "str"
  databaseport: "str"
